name: 编译 "7.0.1-42218"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 同步仓库
        uses: actions/checkout@v2

      - name: 构建工具链
        run: |
          sudo chmod +x rploader.sh
          cp -f user_config.json user_config.json.bak
          
      - name: 编译-3617
        run: |
          cp -f user_config.json.bak user_config.json
          sed -i -e 's\0x0001\0x0002\g' -e 's\0x46f4\0x0002\g' -e 's\1234XXX123\1830ODN005450\g' -e 's\MAC1ADDRESS\245EBE0299E8\g' -e 's\MAC2ADDRESS\001B21BC18BB\g' user_config.json
          ./rploader.sh build broadwell-7.0.1-42218
          ./rploader.sh ext broadwell-7.0.1-42218 add jumkey.acpid2
          ./rploader.sh ext broadwell-7.0.1-42218 add redpill-boot-wait
          ./rploader.sh ext broadwell-7.0.1-42218 add pocopico.mpt3sas
          ./rploader.sh ext broadwell-7.0.1-42218 add pocopico.vmw_pvscsi
          ./rploader.sh ext broadwell-7.0.1-42218 add pocopico.r8125
          ./rploader.sh ext broadwell-7.0.1-42218 add pocopico.ixgbe
          ./rploader.sh auto broadwell-7.0.1-42218
          
      - name: 编译-3615
        run: |
          ./rploader.sh clean all
          sudo rm -rf custom/extensions
          cp -f user_config.json.bak user_config.json
          sed -i -e 's\0x0001\0x0002\g' -e 's\0x46f4\0x0002\g' -e 's\1234XXX123\1630LWN009257\g' -e 's\MAC1ADDRESS\245EBE0299E8\g' -e 's\MAC2ADDRESS\001B21BC18BB\g' user_config.json
          ./rploader.sh build bromolow-7.0.1-42218
          ./rploader.sh ext bromolow-7.0.1-42218 add jumkey.acpid2
          ./rploader.sh ext bromolow-7.0.1-42218 add redpill-boot-wait
          ./rploader.sh ext bromolow-7.0.1-42218 add pocopico.mpt3sas
          ./rploader.sh ext bromolow-7.0.1-42218 add pocopico.vmw_pvscsi
          ./rploader.sh ext bromolow-7.0.1-42218 add pocopico.r8125
          ./rploader.sh ext bromolow-7.0.1-42218 add pocopico.ixgbe
          ./rploader.sh auto bromolow-7.0.1-42218

      - name: 添加扩展驱动-918
        run: |
          ./rploader.sh clean all
          sudo rm -rf custom/extensions
          cp -f user_config.json.bak user_config.json
          sed -i -e 's\0x0001\0x0002\g' -e 's\0x46f4\0x0002\g' -e 's\1234XXX123\1330PDN004175\g' -e 's\MAC1ADDRESS\245EBE0299E8\g' -e 's\MAC2ADDRESS\001B21BC18BB\g' user_config.json
          ./rploader.sh build apollolake-7.0.1-42218
          ./rploader.sh ext apollolake-7.0.1-42218 add jumkey.acpid2
          ./rploader.sh ext apollolake-7.0.1-42218 add redpill-boot-wait
          ./rploader.sh ext apollolake-7.0.1-42218 add pocopico.mpt3sas
          ./rploader.sh ext apollolake-7.0.1-42218 add pocopico.vmw_pvscsi
          ./rploader.sh ext apollolake-7.0.1-42218 add pocopico.r8125
          ./rploader.sh ext apollolake-7.0.1-42218 add pocopico.ixgbe
          ./rploader.sh auto apollolake-7.0.1-42218

      - name: 清理并构建缓存
        run: ./rploader.sh clean all
        
        
      - name: Archive DS3617xs 7.0.1 loader image
        uses: actions/upload-artifact@v2
        with:
          name: redpill-DS3617xs_7.0.1-loader
          path: images/redpill-DS3617xs_7.0*.img

      - name: Archive DS3615xs 7.0.1 loader image
        uses: actions/upload-artifact@v2
        with:
          name: redpill-DS3615xs_7.0.1-loader
          path: images/redpill-DS3615xs_7.0*.img

      - name: Archive DS918+ 7.0.1 loader image
        uses: actions/upload-artifact@v2
        with:
          name: redpill-DS918+_7.0.1-loader
          path: images/redpill-DS918+_7.0*.img
